add additional informations to support script

diff --git a/roles/base/templates/open_support_ssh.j2 b/roles/base/templates/open_support_ssh.j2
--- a/roles/base/templates/open_support_ssh.j2
+++ b/roles/base/templates/open_support_ssh.j2
@@ -1,10 +1,18 @@
 #!/bin/bash
 
+# only run script as root
 if [[ $(/usr/bin/id -u) -ne 0 ]]; then
     echo "Not running as root"
     exit
 fi
 
+# define variables
+SSHKEYS="{{ config_tunnel_ssh_keys }}"
+JITSISERVER="https://www.kuketz-meet.de"
+RANDID=`openssl rand -hex 16`
+
+# define functions
+## simple yes or no function for promts
 confirm() {
     # call with a prompt string or use a default
     read -r -p "$@"" [y/N]: " response
@@ -18,12 +26,15 @@ confirm() {
     esac
 }
 
+## starting teamviewer and set random password
 start_team_viewer() {
   TVPASSWORD=`pwgen 12 1`
   TVID=`teamviewer --info | grep "TeamViewer ID" | cut -d ':' -f2 | xargs | tr -dc '[:alnum:]\n\r' |  sed 's/0m//'`
   sudo killall /opt/teamviewer/tv_bin/TeamViewer >/dev/null 2>&1
+  sleep 1
   sudo teamviewer daemon enable >/dev/null 2>&1
   export DISPLAY=":0.0" >/dev/null 2>&1
+  sleep 1
   teamviewer >/dev/null 2>&1
   sudo teamviewer passwd $TVPASSWORD >/dev/null 2>&1
   # Sending access data
@@ -32,6 +43,7 @@ start_team_viewer() {
   echo -e "ID: $TVID\nPW: $TVPASSWORD"
 }
 
+## the screen session dump with the cloudflared tunnel gets parsed every second to find the cloudflared tunnel URL
 check_for_url() {
     export TURL=""
     touch /tmp/ctun
@@ -41,12 +53,28 @@ check_for_url() {
     done
 }
 
-SSHKEYS="{{ config_tunnel_ssh_keys }}"
-JITSISERVER="https://www.kuketz-meet.de"
-RANDID=`openssl rand -hex 16`
+## defining cleanup function
+function cleanup()
+{
+    # deleting all screen sessions with the name 'cloudflare_tunnel'
+    screen -ls | awk -vFS='\t|[.]' '/cloudflare_tunnel/ {system("screen -S "$2" -X quit")}'
+    # ensure all cloudflared tunnels are terminated
+    sudo killall cloudflared >/dev/null 2>&1
+    # ensure teamviewer ist shutdown
+    sudo teamviewer daemon disable >/dev/null 2>&1
+    # ensure temporary authorized keys are deleted
+    rm -f /root/.ssh/authorized_keys_temp
+    # cleanup temporary logfile from screen session dump
+    rm -f /tmp/ctun
+    # print message
+    echo -e "\e[32mSystem access for support is now closed.\e[0m"
+    sleep 2
+}
 
-# Disclaimer
-echo -e "Opening a support request will grant $SSHKEYS FULL system access. Only proceed if you absolutely trust the listed person!"
+######################################
+
+# printing disclaimer
+echo -e "\e[31mOpening a support request will grant $SSHKEYS temporary full system access as long as this terminal is open. A push message containing the ssh support url and optional the TeamViewer credentials will be send to support.\nOnly proceed if you absolutely trust the listed person!\e[0m\n"
 if ! $(confirm 'Opening support request?') ; then
     echo "EXIT without opening request!"
     sleep 2
@@ -56,8 +84,9 @@ fi
 # Proceed with support request
 echo -e "Please wait until the request tunnel is initiated. [Exit with CTRL+C]"
 
-# Make sure temporary authorized keys file does not exist
-trap "rm -f /root/.ssh/authorized_keys_temp; sudo killall cloudflared; rm -f /tmp/ctun; sudo teamviewer daemon disable" EXIT
+# Make sure access is temporary - as long as script runs
+## trap with cleanup function in case there is an error in the script
+trap cleanup EXIT
 
 # ensure .ssh directory
 mkdir -p /root/.ssh
@@ -84,12 +113,8 @@ echo -e "\n\n"
 # wait until tunnel gets closed
 read -r -p "Type ENTER to exit tunnel" response
 
-# cleanup
-screen -ls | awk -vFS='\t|[.]' '/cloudflare_tunnel/ {system("screen -S "$2" -X quit")}'
-sudo killall cloudflared >/dev/null 2>&1
-sudo teamviewer daemon disable >/dev/null 2>&1
-rm -f /root/.ssh/authorized_keys_temp
-rm -f /tmp/ctun
+# run cleanup
+cleanup
 
 # delete trap
 trap "" EXIT
